//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeadManSwitch.Data.SqlRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeadManSwitchEntities : DbContext
    {
        public DeadManSwitchEntities()
            : base("name=DeadManSwitchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ApplicationSetting> ApplicationSettings { get; set; }
        public DbSet<EscalationActionType> EscalationActionTypes { get; set; }
        public DbSet<KillSwitch> KillSwitches { get; set; }
        public DbSet<KillSwitchRule> KillSwitchRules { get; set; }
        public DbSet<EscalationActionLog> EscalationActionLogs { get; set; }
        public DbSet<CheckIn> CheckIns { get; set; }
        public DbSet<EscalationAttempt> EscalationAttempts { get; set; }
        public DbSet<EscalationWorkTable> EscalationWorkTables { get; set; }
        public DbSet<UserAccount> UserAccounts { get; set; }
        public DbSet<UserEscalationAction> UserEscalationActions { get; set; }
        public DbSet<UserPreference> UserPreferences { get; set; }
        public DbSet<vwMissedCheckIn> vwMissedCheckIns { get; set; }
        public DbSet<ScheduleDaily> ScheduleDailies { get; set; }
    }
}
