//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeadManSwitch.Data.SqlRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EscalationWorkTable
    {
        public int EscalationWorkTableId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModDate { get; set; }
        public int UserEscalationActionId { get; set; }
        public int UserId { get; set; }
        public System.DateTime TriggerDateTime { get; set; }
        public System.DateTime LockExpiration { get; set; }
        public Nullable<bool> Success { get; set; }
        public int NumberOfFailures { get; set; }
    
        public virtual UserEscalationAction UserEscalationAction { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
