//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeadManSwitch.Data.SqlRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class EscalationActionType
    {
        public EscalationActionType()
        {
            this.KillSwitches = new HashSet<KillSwitch>();
            this.UserEscalationActions = new HashSet<UserEscalationAction>();
        }
    
        public int EscalationActionTypeId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModDate { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<KillSwitch> KillSwitches { get; set; }
        public virtual ICollection<UserEscalationAction> UserEscalationActions { get; set; }
    }
}
