//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeadManSwitch.Data.SqlRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class KillSwitchRule
    {
        public int KillSwitchRuleID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModDate { get; set; }
        public int KillSwitchID { get; set; }
        public bool IsActive { get; set; }
        public int Limit { get; set; }
        public long TimePeriodTicks { get; set; }
        public bool ActivateKillSwitch { get; set; }
    
        public virtual KillSwitch KillSwitch { get; set; }
    }
}
