//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeadManSwitch.Data.SqlRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class KillSwitch
    {
        public KillSwitch()
        {
            this.KillSwitchRules = new HashSet<KillSwitchRule>();
        }
    
        public int KillSwitchID { get; set; }
        public System.DateTime ModDate { get; set; }
        public int EscalationActionTypeID { get; set; }
        public string Direction { get; set; }
        public bool Engaged { get; set; }
    
        public virtual EscalationActionType EscalationActionType { get; set; }
        public virtual ICollection<KillSwitchRule> KillSwitchRules { get; set; }
    }
}
