//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeadManSwitch.Data.SqlRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public UserAccount()
        {
            this.CheckIns = new HashSet<CheckIn>();
            this.EscalationWorkTables = new HashSet<EscalationWorkTable>();
            this.UserEscalationActions = new HashSet<UserEscalationAction>();
            this.ScheduleDailies = new HashSet<ScheduleDaily>();
        }
    
        public int UserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModDate { get; set; }
        public string UserName { get; set; }
        public string AccountPassword { get; set; }
        public bool IsActive { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual ICollection<CheckIn> CheckIns { get; set; }
        public virtual ICollection<EscalationWorkTable> EscalationWorkTables { get; set; }
        public virtual ICollection<UserEscalationAction> UserEscalationActions { get; set; }
        public virtual UserPreference UserPreference { get; set; }
        public virtual ICollection<ScheduleDaily> ScheduleDailies { get; set; }
    }
}
