//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeadManSwitch.Data.SqlRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEscalationAction
    {
        public UserEscalationAction()
        {
            this.EscalationWorkTables = new HashSet<EscalationWorkTable>();
        }
    
        public int UserEscalationActionId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModDate { get; set; }
        public int UserId { get; set; }
        public int EscalationActionTypeId { get; set; }
        public int ExecutionOrder { get; set; }
        public long WaitTicksAfterPreviousAction { get; set; }
        public string ActionTarget { get; set; }
        public string ActionMessage { get; set; }
    
        public virtual EscalationActionType EscalationActionType { get; set; }
        public virtual ICollection<EscalationWorkTable> EscalationWorkTables { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
